version: '3.9'

services:
  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SETTINGS_MODULE=config.settings.development
  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
